### ISSUE TITLE
Media-node crashes using 4.x-20230511-nightly

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-docker#37]
Media-node crashes using edumeet/edumeet-media-node:4.x-20230511-nightly

Error msg:
```
2023-05-12T06:58:15.598Z edumeet-media-node:ERROR:MediaNode MediaService creation failed: TypeError: wrong listenInfo.ip (not an string [method:worker.createWebRtcServer] at Channel.processMessage (/usr/src/app/node_modules/mediasoup/node/lib/Channel.js:196:37) at Socket.<anonymous> (/usr/src/app/node_modules/mediasoup/node/lib/Channel.js:69:34) at Socket.emit (node:events:513:28) at Socket.emit (node:domain:489:12) at addChunk (node:internal/streams/readable:324:12) at readableAddChunk (node:internal/streams/readable:297:9) at Readable.push (node:internal/streams/readable:234:10) at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
```

This is my docker-compose.yml:
```
services:
  media_node:
    container_name: "media_node"
    image: edumeet/edumeet-media-node:4.x-20230511-nightly
    network_mode: "host"
    ports:
      - "3000:3000"
      - "40000:49999/tcp"
      - "40000:49999/udp"
    command:
      - --ip
      - "IP REMOVED"
      - --cert
      - "PATH TO CERT REMOVED"
      - --key
      - "PATH TO KEY REMOVED"
      - --secret
      - "SECRET REMOVED"
      - --announcedIp
      - "IP REMOVED"
      - --listenHost
      - "IP REMOVED"
    volumes:
      - type: bind
        read_only: true
        source: /opt/edumeet/certs
        target: /usr/src/app/certs
    restart: unless-stopped
```
